### ISSUE TITLE
Multi-language and/or multi-script support

### ISSUE THREAD

**Issue by erayaydin** [RadKod/parolla-backend#11]
## Suggestion

Current API and back-office only supports `Turkish` 🇹🇷  language and script support. Maybe we can add multi-language and/or multi-script support for publish the application globally.

If this issue accepted, I suggest to implement `English 🇺🇸🇬🇧🇨🇦🇦🇺` , `Dutch 🇳🇱🇧🇪`, `Spanish 🇪🇸`, `French 🇫🇷`, `Italian 🇮🇹` and `Portuguese 🇵🇹` families.

**Comment by erayaydin** [comment]
Are there any news about this issue? @selimdoyranli @apo-bozdag . We can close the issue if its not currently planned.

**Comment by selimdoyranli** [comment]
> Are there any news about this issue? @selimdoyranli @apo-bozdag . We can close the issue if its not currently planned.

We've currently added i18n only to the creative/rooms game mode. When any player create the room, their room is saved according to the selected language. In addition, when any player open the room list, the room list is retrieved according to the selected language. You can see the related developments at this links: (https://github.com/RadKod/parolla-backend/commit/fd980d8bed84850d4cafe5e727d1653f4b62899d, https://github.com/RadKod/parolla/pull/48/files#diff-41392cc7b7840fc62312a949b0032144684dc9f09fe0cd4b9fd12af5295c34c8). There is currently no localization process in the plan for the daily and unlimited game modes, for this we will first need to create our i18n based question pool. I'm closing this issue for now, if you have more questions you can ping me on this issue

**Comment by apo-bozdag** [comment]
> Are there any news about this issue? @selimdoyranli @apo-bozdag . We can close the issue if its not currently planned.

will continue after websocket and scoreboard
